### ISSUE TITLE
Unpopulated metadata.yaml fields are getting overwritten

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#1047]
A recent change to the backend seems to have resulted in [ITIS metadata being overwritten](https://data.catalogueoflife.org/dataset/2144/about) in fields that are not populated in the metadata.yaml file. With the metadata.yaml file below, I think the importer should only update the released and version fields because I only want those fields managed by the converter and importer, and the rest of the metadata to be updatable in the ChecklistBank without the conversion script/importer overwriting changes made in ChecklistBank. Oddly, it also lists @mdoering as the modified by person, and that doesn't seem correct when it was my account that posted the import.

```
released: '2021-08-27'
version: '2021-08-27'
```

The [logs](https://logs.gbif.org/app/discover#/context/37c669c0-2a5c-11eb-9ca0-ddc1af98892f/pvzTonsBBVmQ6cT2_sa8?_g=(filters:!())&_a=(columns:!(level,logger_name,message),filters:!())) don't shed much light on the issue.

**Comment by mdoering** [comment]
It is designed to update all of the metadata when a metadata file is present. 
With the exception of required fields title, alias and license which remain if there is nothing in the incoming archive.
This should have been like this at least since we changed the metadata model, but probably even before that so it's not a recent change.

Detecting which fields are actually present in a YAML or EML file is rather difficult, but is doable. It needs a more basic deserialisation into a generic map structure instead of going to the Dataset object directly. But I still wonder if that is intuitive. If I had listed editors in my first versions and now made them creators instead I would have to leave the editor field in with no value, otherwise both editor and creator would be set. I am not convinced this is intuitive behavior either.

Maybe we can include some instruction in the metadata.yaml, sth like "mergeExistingMetadata: true" which would default to false if not present? If true it would keep all existing metadata and only update the new fields that contain values? That should be straight forward to implement

**Comment by mdoering** [comment]
Or maybe a field _updateMode: merge/replace_ which could take other values in the future?

**Comment by mdoering** [comment]
@gdower the easiest I can think of is to add a dataset setting MERGE_METADATA that defaults to false but if true would change the behavior to only update properties that were provided in the yaml (or EML). This would only work for properties given with some non null value.

Please let me know if you think this is useful or otherwise please close this issue.

**Comment by mdoering** [comment]
The merge metadata settings has been implemented
