### ISSUE TITLE
Does rank "nanorder" applied correctly?

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#1055]
Doing assembly of Dermaptera Species File, I have seen ISSUES report "Classification Rank Order Invalid" with two **nanoders**: Eudermaptera & Plesiodermaptera.

https://data.catalogueoflife.org/dataset/1158/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=classification%20rank%20order%20invalid&limit=50&offset=0

Does "nanoder" rank applied correctly by the checklistbank software?

In the original data:
http://dermaptera.speciesfile.org/Common/basic/Taxa.aspx?TaxonNameID=1179458
  
**subinfraordinal group** Eteodermaptera
   **superfamily group** Eudermaptera
   **subinfraordinal group** Eteodermaptera

**Comment by yroskov** [comment]
@gdower, where corrections might be made (if any needed)?

**Comment by mdoering** [comment]
You can find all ranks here: http://api.catalogueoflife.org/vocab/rank
`nanorder ` is part of that list

**Comment by mdoering** [comment]
https://data.catalogueoflife.org/dataset/1158/taxon/84000

has a hierarchy of:

 - order: Dermaptera de Geer, 1773
 - suborder: Neodermaptera Engel, 2003
 - infraorder: Epidermaptera Engel, 2003
 - parvorder: Eteodermaptera Engel, 2003
 - nanorder: Eudermaptera Verhoeff, 1902

We have placed `nanorder` just below order and above suborder. That's why you see that issue being flagged.
I don't think this will break anything, but just reminds of an unusual use and can often point to serious errors, e.g. a family placed above an order. 

According to Wikipedia nanorder is just below order like we treat it:
https://en.wikipedia.org/wiki/Taxonomic_rank

 - Order
 - Parvorder (position in some zoological classifications)
 - Nanorder (in zoology)
 - Hypoorder (in zoology)
 - Minorder (in zoology)
 - Suborder
 - Infraorder
 - Parvorder (usual position), or microorder (in zoology)
