### ISSUE TITLE
Try to make an API call to get a vernacular Name generates an error

### ISSUE THREAD

**Issue by RicardoOrtizG** [CatalogueOfLife/backend#1115]
I'm trying to use the API to get the vernacular name for a list of species. I tried to use the Checklist bank API, using the option GET/Vernacular, but returns a 500 server error. I don't know if I'm doing something wrong or is due to the undergoing development of the API. 

![imagen](https://user-images.githubusercontent.com/15789737/156261493-44aa87bc-a03b-46b9-8df3-009ba44f8676.png)

**Comment by mdoering** [comment]
There is indeed some bug, likely related to using whitespace in the query. I will fix that today.
But I think you are using the wrong API to do what you want to do.

1) The API is not against Catalogue of Life only, but works against all of ChecklistBank. That is many thousands of taxonomic datasets of all kind. Most of the time you want to only work with one of the datasets, thats why you see most API resources scoped with a datasetKey. The datasetKey for COL is 3, but that refers to the working draft "project" while it is being edited. We publish monthly releases, each as its own, immutable dataset. In order to query always the latest release of a project we accept the suffix LR (LatestRelease) as keys, that is [3LR](https://api.checklistbank.org/dataset/3LR.json) takes you to the latest public release which is 9804 as of today.

2) The global `/vernacular` resource queries vernacular names and returns them. For example query ALL datasets in ChecklistBank to search for "Adler" (German for eagle): https://api.checklistbank.org/vernacular?q=Adler. But _Iguana iguana_ is a scientific name. If you want to list vernacular names for a given species using the latin name you should do so by first identifying the taxon (accepted name usage), then list its vernacular names via the `/taxon/{key}/info` resource. For example to query vernacular names for Iguana iguana in the latest release of the COL Checklist you would do:

    1. Search for _Iguana iguana_ gives you a usage ID of `6MV3G`: https://api.checklistbank.org/dataset/3LR/nameusage/search?rank=SPECIES&content=SCIENTIFIC_NAME&type=EXACT&q=Iguana%20iguana
    2. List all infos including the vernacular names for taxon 6MV3G: https://api.checklistbank.org/dataset/3LR/taxon/6MV3G/info

**Comment by RicardoOrtizG** [comment]
Thanks, Markus for the swift response. what you show me is exactly what I want to do. I'm wondering if there is a restriction in the number of petitions for the API, I have more than 70.000 unique scientific names to match.

**Comment by RicardoOrtizG** [comment]
In python, I'm getting this error, due - as I understand- to a max value of petitions.

![imagen](https://user-images.githubusercontent.com/15789737/156405718-558a6e37-bc4a-46a5-949c-40f318d0260c.png)

**Comment by mdoering** [comment]
No, we do not limit requests at all.
This looks to me like a SSL certificate error. @MattBlissett can you make sense of this?

We are working on a batch matching system that will allow you to match all your names in one go, so you can at least get the COL Identifier in one go. Calling the infos for the vernacular names would still be needed. I might expose a separate resource to list just vernacular names, optionally filtered by a language, to save the overhead of building the large info object.

**Comment by mdoering** [comment]
`/dataset/3LR/taxon/{key}/vernacular` will be the new resource, takes a few hours to deploy

**Comment by MattBlissett** [comment]
What happens if you do this, Ricardo?

```python
> python3
Python 3.9.7 (default, Sep 10 2021, 14:59:43)
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.get("https://api.checklistbank.org/")
<Response [200]>
>>>
```

I would first check you are using an up-to-date version of Python,.

**Comment by RicardoOrtizG** [comment]
Hi Matt, 

I prove your code and get the 200 response too:

![imagen](https://user-images.githubusercontent.com/15789737/156447548-7fa0e800-d0c1-4e25-9026-5d3b34c6f60b.png)

@mdoering thanks, I'm trying first to get the ID to make a request for the vernacularName after that. But the solution you propose sounds great.

**Comment by mdoering** [comment]
works fine for me on MacOS with python 3.9.7.
And also with python 2.7.16 and the latest requests library.

**Comment by RicardoOrtizG** [comment]
Hi!

I try again with a different tool (OpenRefine ) and get no result, it looks like is running but in the end, there is no response. I prove it with only 10 records and with all the names and happens the same.

![imagen](https://user-images.githubusercontent.com/15789737/157133799-e193b27e-ce4a-4c7c-9372-7d50026de882.png)

![imagen](https://user-images.githubusercontent.com/15789737/157134159-29a56256-97e2-458b-810a-c4bdb7619091.png)

**Comment by mdoering** [comment]
This works for me using OpenRefine, this [poa.tsv](https://github.com/CatalogueOfLife/backend/files/8213376/poa.tsv.zip) and a new column defined as:

`"https://api.checklistbank.org/dataset/3LR/nameusage/search?rank="+cells['col:rank'].value+"&content=SCIENTIFIC_NAME&type=EXACT&q="+value.replace(" ", "%20")
`

**Comment by RicardoOrtizG** [comment]
Hi, after many tests I found that the problem was a restriction on the internet page in the institutional network. I tried on Mac without the network restrictions and it runs perfectly. Thanks a lot for your help.
