### ISSUE TITLE
As a user, I'd like to trace the process of compiling Catalogue of Life from their original sources

### ISSUE THREAD

**Issue by jhpoelen** [CatalogueOfLife/backend#1171]
In a GloBI data review, Jeff Ollerton noticed that a name _Aglais io_ was not picked up by an earlier version of the catalogue of life, as versioned by Nomer's Corpus of Taxonomic Resources.

I was able to trace the origins of the suspected false negative name match of _Aglais io_ , showing that an older version of the catalogue of life didn't include the Linnaeus 1758 name, but was recently introduced. See https://github.com/globalbioticinteractions/nomer/issues/124 . 

As far as I understand, the catalogue of life compiles their index from datasets in checklist bank. 

Can you please help me understand how I can trace a name in Catalogue of Life to their original location in the original dataset? For instance, how would I retrieve the versioned digital resources of the Global Lepidoptera Index [1] that was used to populate the Catalogue of Life in period April 2022 - October 2022?  

Thanks for your hard work to compile this massive resource, and am curious to learn more about how you are keeping track of the provenance of your compilation process.

references 

[1]  Beccaloni, G., Scoble, M., Kitching, I., Simonsen, T., Robinson, G., Pitkin, B., Hine, A., Lyal, C., Ollerenshaw, J., Wing, P., & Hobern, D. (2022). Global Lepidoptera Index. In O. Bánki, Y. Roskov, M. Döring, G. Ower, L. Vandepitte, D. Hobern, D. Remsen, P. Schalk, R. E. DeWalt, M. Keping, J. Miller, T. Orrell, R. Aalbu, R. Adlard, E. M. Adriaenssens, C. Aedo, E. Aescht, N. Akkari, S. Alexander, et al., Catalogue of Life Checklist (Version 2022-10-19). https://doi.org/10.48580/dfqf-49xk

**Comment by mdoering** [comment]
COL provides for each name the datasetKey and id from its original source (unless it was directly added to COL like the higher taxonomy). With that you can check the _current_ record with that id.

If you need to go back in time, the only data we keep is the original data archive that was used to import an entire source, e.g. GLI above. You cannot use the API any longer to retrieve a single record as we only keep the latest one. Otherwise we quickly grow out of capacity.

The version of GLI used by COL now is `2022-10-19`:
https://www.catalogueoflife.org/data/dataset/55434

To not depend on human managed metadata we also track a sequential attempt number for dataset imports into CLB as well as an attempt for "syncs" from a datasource to a project like the COL checklist. Each sync in COL remembers the import attempt of the source dataset is had synced from. And for each import attempt we archive the dataset metadata as well as the entire original archive (we only started to archive the entire datasets earlier this year though).

For example the Global Lepidoptera Index currently in COL (=3LR) is:

https://api.checklistbank.org/dataset/3LR/source/55434.json
this claims `attempt:25` which is the import attempt of the dataset used when we last synced it to COL.

You can access the source metadata for that attempt like this:
https://api.checklistbank.org/dataset/55434/import/25.json

Note that the metadata of the dataset might be different from the one in the project (COL) as we allow project editors to "patch" parts of the metadata - e.g. to have a different description as we only use a part of the source, a consistent short name or adding missing author ORCIDs.


This gives you stats as well as a MD5 hash of the archive used.

The binary archive for that attempt can be retrieved with:
https://api.checklistbank.org/dataset/55434/archive?attempt=25

You can see all imports in the history sidecar here with access to stats, logs, the archive itself and a quick name browser:
https://www.checklistbank.org/dataset/55434/imports

<img width="1580" alt="image" src="https://user-images.githubusercontent.com/327505/200333585-79345695-f5f8-4b9c-830c-7de94c2867fd.png">

**Comment by jhpoelen** [comment]
@mdoering thanks for taking the time to respond to my request to trace the process of compiling the calalogue of life from their original sources.

Neat to see the history associated with original datasets, and associated visualizations of the changes and statistics of their contents. 

I used the history feature to attempt to download @dhobern 's Jun 29, 2022 12:47 AM version of the Global Lepidoptera Index via https://www.checklistbank.org/dataset/55434/imports/6 and, for some reason, I was unable to retrieve the original copy - 

![image](https://user-images.githubusercontent.com/1084872/200343249-ffa3b1f9-3dca-4c3e-bcd3-1070654b0989.png)


Is this expected? 

Also, is there a way to get access to the Catalogue of Life's equivalent of a make script? 

I assume that there's an automated process to compile your input data and generate the search index that helps power the Calalogue of Life API . If there's a way to access this COL Makefile, folks should be able to independently recreate the search index from scratch, including all the custom patches that curators have created.

**Comment by mdoering** [comment]
Yes thats expected. We only archive original dataset archives since August this year: https://www.catalogueoflife.org/2022/08/15/archive-repository

We always kept the metadata and metrics, but the archives are only accessible since that time I am afraid.

I am not entirely sure I understand your make script idea. The entire implementation is in Java (with Maven), so there is no script involved to either do dataset imports, sector syncs or releases - all of which are involved to create a project like the COL Checklist. I wished we had a diagram for the workflow as it grew a bit more complex than it initially sounds...

**Comment by jhpoelen** [comment]
> Yes thats expected. We only archive original dataset archives since August this year: https://www.catalogueoflife.org/2022/08/15/archive-repository

Thanks for confirming that you did not archive https://www.checklistbank.org/dataset/55434/imports/6 .

>  am not entirely sure I understand your make script idea. The entire implementation is in Java (with Maven), so there is no script involved to either do dataset imports, sector syncs or releases - all of which are involved to create a project like the COL Checklist. I wished we had a diagram for the workflow as it grew a bit more complex than it initially sounds...

By script, I meant some automated process you can run to compile a catalogue of life from their sources. So, a java/mvn setup would do just fine. 

I got all the sources of the catalogue of life, how do I go about building a copy of the catalogue of life from them using your java program? Can you show an example?

Thanks for being patient with me as I am trying to understand the catalogue of life compilation process.

**Comment by mdoering** [comment]
That is not easily possible at all. You need all the sector mappings, editorial decisions, etc. Basically a copy of the entire project in checklistbank with previous releases to also yield the same identifiers and then run your own checklistbank instance.

**Comment by jhpoelen** [comment]
@mdoering thanks for clarifying. I am sure there's good reasons for the current Catalogue of Life architecture. And, with this exchange, I realize that publishing editorial decisions as separate datasets might help to re-annotate existing original datasets. This re-annotation might make it easier to compile a taxonomic resource like the Catalogue of Life from scratch.
