### ISSUE TITLE
Add more facets like epithet

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#371]
Adding more facets for parsed names to the search index would be very useful:
 - epithet: both species or infraspecific epithet
 - genus: genus part of the name
 - author: a single author from any of the 2 authorships (comb/bas) including ex authors
 - year: the year from any of the 2 authorships (comb/bas)
 - code: the nomenclatural code

Adding a new facet requires to:
 - add a new NameSearchParameter enum value
 - change elastics schema

**Comment by ayco-at-naturalis** [comment]
This would be very easy, because I have already included them (at least the epithets) separately in the index

**Comment by ayco-at-naturalis** [comment]
@mdoering In order to create facets for authorship and year, I have added two new NameUsageSearchParameters: AUTHORSHIP and AUTHORSHIP_YEAR

I have also added 2 new fields to the document:

1. authorship (Set<String>)
2. authorshipYear (Set<String>)

I think it's not necessary to choose a single author/year, since Elasticsearch is intrinsically multi-valued, unless you had another reason to restrict it to one value.

The original authorship field I have renamed to authorshipComplete. I didn't map AUTHORSHIP to the original authorship (i.e. authorshipComplete) but to the new authorship field, because (with my limited taxonomic knowledge, it didn't seem to make much sense to facet on (group by) a long, derived authorship string. Correct?

Since you intended the new fields to be used primarily as facets, it seems to me the frontend would need an extra service to get all distinct authors (for a dataset), or do I miss something?

I have not commited any of this yet, so let me know if this sounds alright.

**Comment by ayco-at-naturalis** [comment]
Ah - no forget about the service, the facets come along with the entire query result

**Comment by ayco-at-naturalis** [comment]
@mdoering I took a chance and assumed I have interpreted the requirements correctly. After I had created a [unit test](https://github.com/CatalogueOfLife/backend/blob/master/dao/src/test/java/life/catalogue/es/nu/search/NameUsageSearchParameterTest.java#L757) for author/year it just looked to natural. If not, we only have the remove the new authorship field and rename the authorshipComplete field back to authorship (well, plus the NameUsageWrapperConverter).

**Comment by ayco-at-naturalis** [comment]
So, to resume (also relevant for @gdower en Thomas),

There are 2 new name usage search query parameters:

1. authorship
2. authorshipYear

They are primarily meant for faceting, although you can of course also use them as filters. The facets are of **individual** authors. No distrinction is made between basionym authorship authors or combination authorship authors. If an (Elasticsearch) name usage document has "Jim" as a basionym author or a combination author, that add to the document count for facet "Jim".

**Comment by ayco-at-naturalis** [comment]
Oh, one more thing - I'm afraid  this requires a full index, but it would have been necessary even for just the authorship **year**

**Comment by mdoering** [comment]
Sounds good! Ill give it a try on dev today

**Comment by mdoering** [comment]
@thomasstjerne adding all facets to advanced search wojld be great if thats simple. maybe even dynamically by checking all avail search params in the vocab service so they become available if we add more?

**Comment by thomasstjerne** [comment]
I dont quite understand. Facets in the current UI is for Enums , i.e. x number of species, x number of families etc
I guess facetting on Epithet would give all the epithets in the dataset, starting with those that have autonyms (facet count 2 for specific and intraspecific epithets) and those that are used in more than one genus?

**Comment by ayco-at-naturalis** [comment]
@thomasstjerne Well, as I mentioned above, the top-50 values for a facet like author come along with the query result purely by virtue of specifying &facet=author. But I must admit that might make the user never see past that top-50 unless he is able to specify a filter with exactly the right name (case sensitivity and all) of a particular author, like &author=John+Smith. Which is why I was thinking of the service mentioned above.

**Comment by mdoering** [comment]
If you filter by a family for example it should be useful to see the top 10, 25 or 50 authors (or their spelling variants). For epithets it might indeed not be very useful on the search page.

Maybe this is more something for metrics on a higher taxon page? Lets play with the API first
