### ISSUE TITLE
Name search: order of data is affected when a decision is applied

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#547]
When a descision is applied in the workbench, if you reload the page you won´t see the decision.
Reason: the row is now in the end of the result set.

Example: I applied decisions to the two very first rows of this result set (Bilimbia and Bilimbia) and now they are in the page offsetting at 29150
https://api-dev.col.plus/dataset/2046/name/search?facet=rank&facet=issue&facet=status&limit=50&offset=29150&reverse=false

**Comment by ayco-at-naturalis** [comment]
@thomasstjerne  Just adding "reverse=false" currently won't do anything. The "reverse" param only works when sorting on name or taxonomically). I guess what you want is: show documents in reverse order of how they were indexed. I will add this possibility

**Comment by thomasstjerne** [comment]
This still apply.
to replicate:
1. Got to the [workbench and filter by e.g. species rank](https://data.dev.catalogue.life/catalogue/31450/dataset/31451/workbench?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0&rank=species)
2. Add some decisions
3. Reload the page

Now the rows with decisions has moved to the end of the result set, most often on another page (if there are more than 1 page).
This is confusing for the user as the data he/she works on suddenly seems to disappear.

Currently the frontend has been adjusted to avoid reloading data on a page, but this leaves the responsibility of attaching decisions to data "in place" in the table, rather than doing a reload to get updated data from the server.

**Comment by mdoering** [comment]
That is because the UI does not specify any sort order. If no sortBy parameter is given, the order defaults to NATIVE which is elastics native ordering by `_doc` and it seems that changes when a record is modified. So I would recommend you always use some sort order in the workbench, even if not explicitly given by the user. 

Ah, I think the reason is we dont use taxonID as the document id in elastic but let elastic manage its own ids. So when we reindex a document we delete and then recreate it - which will assign a new document id - which is likely at the end of the range. @ayco-at-naturalis does that explain it?

**Comment by mdoering** [comment]
only option to change this in the backend is to refrain from letting ES manage its document ids. Which would be a serious change to the search code that we cannot handle at this stage
