### ISSUE TITLE
Keep subject IDs in decisions

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#607]
Currently the backend [removes the subject ID for decisions when it's not able to rematch the decision](https://github.com/Sp2000/colplus-backend/issues/346#issuecomment-570721236) in order to mark the decisions as broken. We can discuss this more when @mdoering gets back, but I think instead a broken boolean should be set, and the subject ID should always be retained. Otherwise if some intermittent issue causes a large number of decisions to not match for some reason, the backend would delete the subject IDs which could wipe out a lot of work.

Removing the subject IDs also makes debugging the decisions API harder.

**Comment by mdoering** [comment]
we have a setting `REMATCH_DECISIONS` now that defaults to false. Only if true decisions are automatically rematched on imports

**Comment by mdoering** [comment]
Reopening because we want the ids to remain for broken decisions so we later still know what they referred to. We should not delete ids. Question:

 - should we just keep the latest matched id and flag broken decisions?
 - should we forever track the initial id the decision had when created? Even if a subsequent rematching matched to a different record?

**Comment by gdower** [comment]
Having original_subject_id will be useful for debugging the broken decisions. :+1:
