### ISSUE TITLE
Report on duplicated taxa in GSD vs rest of the CoL

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#629]
One of important components of editorial preparation of the GSD for assembly in CoL is a report for duplicated accepted names (all ranks) between the GSD and rest of the CoL. This helps to catch conflicts in the classification and make decision which sectors should be excluded from the GSD or from CoL.

We already have nicely developed tools such as **Dataset-Tasks** (report on duplicates inside GSD) and **Catalogue-Duplicates** (report for all duplicates across CoL). Neither of them contains report on duplicates in **GSD vs CoL**. 

Report on duplicates in GSD vs CoL might be displayed on Dataset-Tasks page as an additional batch of reports **GSD vs CoL**, organized in the same style as internal reports for GSD “Identical genus”, “Identical family”, … “Identical phylum”. One additional column need be added in the report:
ID|Decision|**Dataset** [i.e. short name of GSD]|Status|Uninomial|Authorship|Rank|Classification

**Comment by mdoering** [comment]
I agree this is important and is part of a more generic dataset comparison tool that should exist in the Clearinghouse. Comparing 2 datasets or a sector within one of them is a frequent and time consuming task. Spotting duplicates, different accepted names, variations in classifications, names at different ranks, differences in nomenclatural references, etc.

When we first designed the duplication tool we envisioned all duplication detection would happen within the catalogue after a sync was done. Decisions would then be made and the sync repeated until the integrated data is accepted.

**Comment by mdoering** [comment]
To spot duplicates between a GSD and the entire CoL I propose to sync the GSD into the working draft and then look for duplicates in the entire CoL. The problem with this currently is that the entire CoL has so many duplicates it becomes unmanageable to review all duplicates.

For this I propose to:

 - add a new sourceDatasetKey parameter to the duplicate API so that at least one of the names in the duplicate has to come from that source dataset. This allows to just show duplicates that involve a single GSD.
 - use the REVIEWED decision for duplicates in the draft that exist for good reasons and to document that reason in the notes field of the decision. Over time this will allow us to filter out all good duplicates and only focus on new ones

@thomasstjerne I will open a UI ticket for adding a new sourceDatasetKey parameter to the duplicate page when that shows a project, not a source like here: 
https://data.dev.catalogue.life/catalogue/3/duplicates?limit=50&offset=0

**Comment by mdoering** [comment]
https://github.com/CatalogueOfLife/clearinghouse-ui/issues/624
