### ISSUE TITLE
Make dataset origin immutable

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#634]
Do not allow dataset origin to be changed and restrict the enumeration to just `external` or `managed`. Uploading archives should be possible for both kind of datasets.

**Comment by mdoering** [comment]
plus maybe `release` as an origin so we can easily distinguish datasets actively worked on from immutable ones

**Comment by thomasstjerne** [comment]
Its of course possible.
Just wondering, couldnt it be confusing looking at an external dataset and believing this is the data as it came from a source, but actually someone uploaded an archive?

**Comment by mdoering** [comment]
Yes. It is confusing now also that you can change the origin. Make it uploaded, upload data, change to sth else. 

Maybe uploading should only be supported for managed datasets?

**Comment by gdower** [comment]
I like the idea of the external, managed, and release datasets. I see your point about  it being confusing to override the external URL with an upload. It seems like uploading should be possible for external datasets though, because uploaded files are by definition external. Maybe the backend should hide the URL when it is overridden with an upload, or there should be a warning next to it?

We might need to temporarily replace a external URL dataset with an upload and test assembly, particularly in coming months when we are working on testing the automated GSDs (WoRMS, PARIS, etc.). Ideally, the URL would be kept in the dataset registration instead of having to go back and re-register the URL again.

**Comment by mdoering** [comment]
thats what I had thought. So lets simply allow uploads to both, but maybe indicate in an import metric how the specific import was done (url or upload file name). Then its traceable

**Comment by mdoering** [comment]
The imports do have an origin now
