### ISSUE TITLE
Unauthorized to delete names

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#695]
On dev I was trying to delete a name that I created on a throwaway managed dataset with the following API call but got a 403 user not authorized error:

`DEL https://api.dev.catalogue.life/dataset/31512/name/79c6ff31-45cb-4b68-abe1-a3479643d135`

Is that the correct API call to delete names, or is it an authentication bug?

**Comment by mdoering** [comment]
That looks correct to me. In order to delete you need to authenticate.
Unless you did authenticate this is very much expected behavior.

The dataset 31512 was created by user 102 which is also the only editor:
https://api.dev.catalogue.life/dataset/31512
```
{
  "created": "2020-04-23T19:37:00.984531",
  "createdBy": 102,
  "modified": "2020-04-23T19:37:00.984531",
  "modifiedBy": 102,
  "key": 31512,
  "type": "taxonomic",
  "origin": "managed",
  "locked": false,
  "title": "GDO Test assembly",
  "license": "other",
  "importFrequency": "never",
  "deleted": "2020-04-23T21:04:55.331145",
  "settings": {
    "rematch decisions": false
  },
  "editors": [
    102
  ],
  "private": false
}
```

And user 102 is you and has editing access to 31512
https://api.dev.catalogue.life/user/102
```
{
  "key": 102,
  "username": "gdower",
  "firstname": "Geoff",
  "lastname": "Ower",
  "country": "US",
  "datasets": [
    2049,
    31521,
    31459,
    31513,
    31512,
    31517,
    31516,
    31497,
    31510,
    31507,
    2051,
    31523,
    31449,
    31515,
    31519,
    31514,
    31518,
    1206,
    2052,
    3,
    1141,
    31520,
    31445,
    31448,
    31522,
    31442,
    31444,
    31441,
    1052
  ]
}
```
