### ISSUE TITLE
Importer field names

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#752]
I'm making Access templates for CoLDP and `name` in the `VernacularName` table is a reserved word. I changed the field name to `vernacularName` in the Access template. Will the importer be able to recognize `vernacularName` as `VernacularName`.`name`? Are there vocab mappings for the field names that I can update?

**Comment by gdower** [comment]
Access complains about the `Name` table name being a reserved word, too.

**Comment by mdoering** [comment]
How is this MS Access problem related to the backend? You need to provide an export to CSV/TSV files for the backend importer to work with. And in that process you can rename the fields/table names you had to change because auf reseved names in Access. The importer will not recognize VernacularName(.csv).vernacularName if that is the question
