### ISSUE TITLE
Facilitate "species or below"

### ISSUE THREAD

**Issue by ayco-at-naturalis** [CatalogueOfLife/backend#754]
I've now also started to use the col+ api in a project and noticed that it would be useful to allow for "species or below" searches. Perhaps with an enum RANK_EQUALS, RANK_LTE, RANK_GTE, RANK_BETWEEN (the 2nd and 3rd enforcing acactly 1 rank is specified; the 4th exactly 2)

**Comment by mdoering** [comment]
Agree. You can do this now only by supplying all ranks for species and below.
We actually do have a Rank.INFRASPECIFIC_NAME and Rank.INFRASUBSPECIFIC_NAME as rank groups. Instead of matching the search to exactly these rank values we could interpret these searches to match against all ranks below species or subspecies. Then a query for species and below would just have to supply to ranks (SPECIES & INFRASPECIFIC_NAME). This is a very simple way of adressing the problem without hardly any change in the code nor index. But it would take away our ability to search for records with exactly rank=INFRASPECIFIC_NAME, which might be needed to find specific problems.

How about adding 2 new search parameters minRank & maxRank which we use elsewhere already. The backend can easily translate this into an OR search using the existing rank parameter then without the need to change the index.

**Comment by ayco-at-naturalis** [comment]
Yes, that sounds good, too. If you like I could it this. I still also need to check your fix for decisions. Had a strange feeling about it, but that may be just because I'm traumatised by nasty logical surprises when querying on nested documents

**Comment by mdoering** [comment]
I already did, but please review it
