### ISSUE TITLE
Problem with search in assembly

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#772]
Frontend version: c99dba2 June 17, 2020 9:47 AMBackend version: 507800e June 17, 2020 8:53 AM
@mdoering 

The system was not able to find genus **Cheilanthes** neither in the tree of CoL Working Draft (left) nor in the tree of the source GSD World Ferns (right), despite this genus is present in both trees.

"Empty" search in left tree:
![image](https://user-images.githubusercontent.com/28574252/85866319-d54b2e80-b78c-11ea-989d-8b880b55a778.png)

"Empty" search in right tree:
![image](https://user-images.githubusercontent.com/28574252/85866417-f7dd4780-b78c-11ea-8bbb-cc7088d37347.png)

Manually expanded trees (left & right):
![image](https://user-images.githubusercontent.com/28574252/85866144-94531a00-b78c-11ea-8985-1b02b8541d92.png)

**Comment by gdower** [comment]
@ayco-at-naturalis, this might be an issue with the suggest service. If you remove the last character, suggest works but when provided with the full name suggest does not return anything:

Full name:
https://api.catalogue.life/dataset/3/nameusage/suggest?vernaculars=false&fuzzy=false&limit=25&q=Cheilanthes

Last character deleted:
https://api.catalogue.life/dataset/3/nameusage/suggest?vernaculars=false&fuzzy=false&limit=25&q=Cheilanthe

**Comment by mdoering** [comment]
@ayco-at-naturalis the max_gram settings for sciname_autocomplete_indextime are 10, so it seems whenever the query exceeds 10 it does not match anymore: https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-edgengram-tokenizer.html#max-gram-limits suggest to use a [truncate filter for queries](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-truncate-tokenfilter.html).

**Comment by mdoering** [comment]
@ayco-at-naturalis, am I correct that NameUsageSuggestionServiceEs does a first analyze only POST request via EsUtil before it actually passes on the suggest request? Cant that be done in one go? Should a suggest request actually use the same analyzer than we use for indexing? The above link recommends otherwise.

**Comment by mdoering** [comment]
looks to me like we need to reestablish a `sciname_autocomplete_querytime` analyzer for SCINAME_AUTO_COMPLETE that makes use of the truncate filter

**Comment by ayco-at-naturalis** [comment]
The solution to the problem with non-fuzzy searching was quite a bit more involved than I expected, but as a consequence Q matching is quite a bit more gründlich

Note that **implicitly** we have in fact three pairs of mutually exlusive options:

- fuzzy <-> non-fuzzy (I now call this "simple" in the code)
- prefix <-> whole-words
- match all terms (AND) <-> match any term (OR)

The choice between fuzzy and non-fuzzy matching is totally up to the user both for search and suggest. Thie choice between prefix and whole-word matching is up to the user for search; for suggest it's always prefix.

The last pair gets hard-coded to AND. This is not relevant for epithet matching (because we match one search term against one epithet). But it is still relevant, because we have a fallback query against the full scientific name. Thus "croco dundee" does not match "Crocodylus".

@mdoering If it turns out to be nice/required to give the user the option to choose between match all and match any, just alter [QMatcher.sciNameBaseQuery](https://github.com/CatalogueOfLife/backend/blob/master/dao/src/main/java/life/catalogue/es/nu/QMatcher.java#L101) slightly:


```java
  DisMaxQuery sciNameBaseQuery() {
    return new DisMaxQuery()
        // Make sure exact matches (even on small scientific names like genus "Ara") always prevail
        .subquery(new SciNameEqualsQuery(FLD_SCINAME, request.getQ()).withBoost(100.0))
        .subquery(new SciNameMatchQuery(FLD_SCINAME, request.getQ()).withOperator(OR));
  }
```

**Comment by mdoering** [comment]
deployed to dev & prod just now

**Comment by mdoering** [comment]
Hm, the API call now returns for [Cheilanthes](https://api.catalogue.life/dataset/3/nameusage/suggest?fuzzy=false&limit=25&q=Cheilanthes), but nothing for a shorter version like [Cheilanth](https://api.catalogue.life/dataset/3/nameusage/suggest?fuzzy=false&limit=25&q=Cheilanth)

@ayco-at-naturalis do you have an idea what that could be?
Do we need to reindex? I thought the change was just the search analyzer, not the indexing one.

**Comment by ayco-at-naturalis** [comment]
@mdoering pff, I'll look

**Comment by ayco-at-naturalis** [comment]
Hm, the [Cheilanthes unit tests](https://github.com/CatalogueOfLife/backend/blob/master/dao/src/test/java/life/catalogue/es/nu/suggest/CheilanthesTest.java) actually pass. Just pushed to see what happens on Jenkins.

**Comment by ayco-at-naturalis** [comment]
I **did** make the epithets in the NameStrings object multi-valued. At first they were String; now they are String[]. At first they only contained the normalized version; now they contain the literal name plus, if different, the normalized version.

However, that shouldn't make a difference and anyhow the tests pass both with fuzzy=true and fuzzy=false.
