### ISSUE TITLE
Subspecies assigned issue is sometimes incorrectly flagged

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#788]
The `subspecies assigned` issue is incorrectly applied to this name:

scientificName: Lutzomyia (Helcocyrtomyia) osornoi
authors: (Ristorcelli & Van ty, 1941)

See here or import the [attached zip](https://github.com/CatalogueOfLife/backend/files/4961235/subspecies_assigned_bug.zip) in case dev gets wiped:

https://data.dev.catalogue.life/dataset/2052/verbatim?issue=subspecies%20assigned

It looks like maybe the scientificName and authors fields get concatenated and then parsed, and maybe the ty is wrongly interpreted as a subspecies? The ty is not actually assigned as a subspecies in the interpreted data, which is good. 

When we are provided with atomized data that does not need to be parsed, the user probably does not need to know about all these debug level parser problems, especially when no subspecies was actually assigned.

**Comment by mdoering** [comment]
Its because of the `Van ty` author which gets badly parsed. I'll see if I can improve this and similar

**Comment by mdoering** [comment]
I have implemented the parseAuthorship routine of the name parser with a proper custom authorship only parsing routine instead of the default one which simply parsed `Abies alba {AUTHORSHIP}` and used the full name parsing which introduced much more ambiguities as needed. This change should improve many more parsed authorships if they are given separate from the rest of the name!

**Comment by mdoering** [comment]
imports fine now: https://data.dev.catalogue.life/dataset/2052/name/CIP-82
