### ISSUE TITLE
Deletion of Arachnida sector failed

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#800]
Frontend version: 73e66a2 August 4, 2020 9:02 AMBackend version: 8aee689 August 6, 2020 2:26 AM

I need to update classification in Arachnida with latest ITIS. To do that, I have Deleted Subtree class Arachnida, then, assembled subclass Arachnida from ITIS, and synced it. Third step should be Delete Sector Arachnida. Expected behavior: full classification in subclass Arachnida will stay in the tree for further assembly of GSD sectors . 

However, deletion is failed: 
PSQLException: ERROR: update or delete on table "name_usage_3" violates foreign key constraint "name_usage_3_parent_id_fk" on table "name_usage_3" Detail: Key (id)=(66675b61-2419-45ce-9455-3bfcde815fe4) is still referenced from table "name_usage_3".

![image](https://user-images.githubusercontent.com/28574252/89939277-53e51980-dbdd-11ea-8dd3-e8670d53db77.png)

**Comment by mdoering** [comment]
I will investigate. 
Let me first make sure I understand the procedure you applied. You deleted the old Arachnida class tree incl all its sectors, then created a new subclass sector from ITIS, synced it and deleted it again so you have all genera in the draft attributed to the CoL classification to start with the real assembly of various sectors? And the last sector delete step failed various times?

Why not leave the new subclass ITIS sector and just replace the taxa that you want to source from different datasets instead of deleting it?

**Comment by yroskov** [comment]
Yes, you description of my plan is correct.

**Comment by yroskov** [comment]
>Why not leave the new subclass ITIS sector and just replace the taxa that you want to source from different datasets instead of deleting it?

Because majority of taxa in Arachnida-ITIS have regional coverage; they should have only classification in CoL with empty species level.

**Comment by yroskov** [comment]
2020-08-12
Frontend version: 1b442e9 August 12, 2020 4:38 AMBackend version: 9b67c47 August 12, 2020 6:42 AM

The same problem remains: unable to delete Arachnida sector from CoL-draft.

![image](https://user-images.githubusercontent.com/28574252/90048009-78ea9280-dc98-11ea-9792-4ecfb4a3bcc2.png)

**Comment by mdoering** [comment]
Yes, the issue isn't closed yet

**Comment by yroskov** [comment]
Is this fix a priority on your desk? Right now we cannot move forward with ITIS until it fixed.

**Comment by mdoering** [comment]
The problem is that there are zoological [sections](https://en.wikipedia.org/wiki/Section_(biology)) in the sector.
The rank section is used in the (most frequently used) botanical sense in the code, so it expects it to be below genera and thus to be deleted. Its the parent of superfamilies though which remain, causing a constraint violation.

I will change the rank manually from section to sth else for now and run the deletion again.

**Comment by mdoering** [comment]
I had to temporarily change 4 sections but now they are reverted and the delete went through fine.
