### ISSUE TITLE
Create extra ranks that are called the same but diverge between the codes

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#801]
The following [ranks](https://en.wikipedia.org/wiki/Taxonomic_rank#All_ranks) are sorted/ranked differently in the zoological and botanical code but they share the same name and currently the same rank enum value in the java code:

 - section
 - subsection
 - series

This causes troubles like #800 when the logic is based on the correct ordering of ranks.
To avoid this we need to create separate rank entries:

 - SECTION_ZOO (above SUBSECTION_ZOO)
 - SECTION_BOT (above SUBSECTION_BOT)
 - SUBSECTION_ZOO (above Giga/Megafamily)
 - SUBSECTION_BOT (above Series)
 - SERIES_FISH (above Order)
 - SERIES_LEPIDOPTERA (above Family)
 - SERIES_BOT (above SpeciesAggregate)

When interpreting a single name without knowing its code or taxonomic position it is nearly impossible to infer which exact rank it is. But the importer might know about the nomenclatural code and thus infer that "section" was meant to mean SECTION_ZOO. For fishes and Lepidoptera it is more difficult as we also need to know the taxonomic context. Maybe we can live with just a single SERIES_ZOO entry, but where? [NOMEN](https://github.com/SpeciesFileGroup/nomen/blob/master/src/ontology/nomen.owl) does not have any entry for a zoological series. @dhobern from your work on Lepidoptera is the use of rank `series` just above family common?

**Comment by mdoering** [comment]
@NicBailly are you aware of the use of the rank `series` in fishes?

**Comment by NicBailly** [comment]
It is not frequent but FIshes of the World which is the book of reference for the complete classification of fishes has used it for the first time in its 5th edition of 2016. It is used there at order level, between Superorder and Order (!), incl. Subseries and Infraseries. We used it as well in Betancur-R et al 2017 but above the Ssuperorder rank so it can be interpreted either at class or Order level As it is, it makes more sense at order level since at the class level we use division. But it is a personal view.

**Comment by mdoering** [comment]
Interesting and a bit painful. @dhobern what does the Lepidoptera world look like?
I am inclined to suggest a single zoological `series` rank that we place between Superorder and Order.

**Comment by mdoering** [comment]
I think I rather stick with what we got and use the same rank enum value for botany and zoology.
We mark those ranks as ambiguous in their ordering so code knows the exact placement of those names might vary. Especially when it's even handled differently within zoology.

**Comment by dhobern** [comment]
That seems sensible. FWIW - I've never seen these ranks used for Lepidoptera. There again, Lepidoptera is just an order, so supraordinal nonsense doesn't affect it.

**Comment by mdoering** [comment]
@dhobern according to Wikipedia series is used just above family level in Lepidoptera. But I found a better workaround with flagging certain ranks as "ambiguous" in their placement so I don't think we need to create separate enum entries for the respective codes anymore

**Comment by NicBailly** [comment]
@mdoering @dhobern

Sorry for this long emails.

I am not found of rank sequence (i.e., superrank, rank, subrank, infrarank, etc) being inserted in the middle of another one (as Markus proposes following Fishes of the World: but I don't think we will adopt this edition as is in FishBase, too many little issues like that). When Fishes of the World inserted the Series sequence in the middle of the Order sequence, i.e., between the Superorder and Order ranks, I guess it is because they wanted to keep some names at the same rank between the 4th and 5th editions, rather than keeping the same name and move it from Superorder to Series. There are pros and cons for the two types of change: change of rank for the same name, change of rank coining a new name, e.g., with a different suffix.

But I would argue that imbricating rank sequences goes against the usefulness of ranks because it makes long classification difficult to read, since you are never sure if Superrank would be followed by rank or another rank sequence.
I would favour to keep rank sequence strictly ... sequential:

... (there are other prefixes like mega)
Superrank1
 Rank1
  Subrank1
   Infrarank1
''' (there are other suffixes like parv)
... (there are other prefixes like mega)
Superrank2
 Rank2
  Subrank2
   Infrarank2
''' (there are other suffixes like parv)

etc.

And not:

... (there are other prefixes like mega)
Superrank1
 Rank1
... (there are other prefixes like mega)
Superrank2
 Rank2
  Subrank2
   Infrarank2
''' (there are other suffixes like parv)
  Subrank1
   Infrarank1
''' (there are other suffixes like parv)

The corollary of that is if new analyses define new clades between, e.g., between Order and Suborder, you need to change the rank for some names in previous classification.

About the ranking of Series, Division, Clade, I think it is variable in the literature not only between Zoology and Botany, but also at least within Zoology (and I guess within Botany as well). Taxonomists usually don't like normative rules, but it is exactly what Garnett & Christidis complain about, because this variability of classification representation in addition to the taxonomic changes does not make the life easy, e.g., for ministry of environment where they have to assemble several classification schemas with same rank name but different ranking.

Within CoL, we could search for new solutions of presenting classifications, including how insert ranks (not rank sequences as define above) within a rank sequence to keep well known names at the same rank for the sake of some stability, at least as long as the phylogeny is not completely changed. I proposed that in 2 or 3 CoL meetings but did not have success so far. Maybe looking for funds for meetings (even zoom ones, e.g., to pay a convenor and a rapporter) and preparatory work to start discussions ...

**Comment by mdoering** [comment]
Thanks @NicBailly This is the approach we currently take with the [current Rank enumeration](https://github.com/gbif/name-parser/blob/master/name-parser-api/src/main/java/org/gbif/nameparser/api/Rank.java#L36)

**Comment by NicBailly** [comment]
@mdoering Ok, it is what I understood reading between lines. But we should avoid to endorse imbrication.
