### ISSUE TITLE
Error 400 in Tasks

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#848]
Frontend version: 0e34f62 September 18, 2020 2:04 AMBackend version: ce3a5b1 September 18, 2020 2:34 AM
@mdoering @thomasstjerne; @gdower  

I am resolving Tasks in World Plants on prod. 

_SYN-SYN species (different accepted, different authors)._ 

My steps: 1. Selected all synonyms, 2. Picked up decision "ambiguous synonym", 3. Applied decision.

Result: Batch of names (not all) failed to get status "ambiguous synonym".

![image](https://user-images.githubusercontent.com/28574252/93791753-410d2e00-fbfa-11ea-98e3-97430598b09a.png)

**Comment by yroskov** [comment]
The same Error:

_SYN-SYN species (different accepted, different authors)._

https://data.catalogue.life/catalogue/3/dataset/1141/duplicates?acceptedDifferent=true&authorshipDifferent=false&category=binomial&limit=500&minSize=2&mode=STRICT&offset=0&status=synonym&withDecision=false

![image](https://user-images.githubusercontent.com/28574252/93802074-99e3c300-fc08-11ea-8132-7a5aeb312635.png)

**Comment by yroskov** [comment]
Also Error:

_SYN-SYN species (same accepted, same authors)._   

Decision "block all synonyms" failed. 

![image](https://user-images.githubusercontent.com/28574252/93802702-6a818600-fc09-11ea-9d30-91f7169e58d2.png)

**Comment by mdoering** [comment]
POSTing the decision yields the _bad request_ 400 error.
The response is 
```
 {
    "code": 400,
    "message": "Decision already exists"
}
```

@thomasstjerne it would be good to show the error message not just the failed with status 400 which does not say much to a user. That would at least explain whats going on.

Wow. But this is indeed a backend bug. There are no duplicate decisions. I am surprised noone has noticed this before.
Fixed in code, but needs [some other frontend change](https://github.com/CatalogueOfLife/clearinghouse-ui/issues/723) by @thomasstjerne before I can deploy the fix to prod

**Comment by mdoering** [comment]
@yroskov @gdower @thomasstjerne Until we deploy to prod NO DECISION can be created from anywhere

**Comment by yroskov** [comment]
> Until we deploy to prod NO DECISION can be created from anywhere

OK. I am switching from "decision" to a "check" mode until greenlight from you.

**Comment by mdoering** [comment]
green light, deployed to prod
