### ISSUE TITLE
Docs have: `/nameusage/suggest` - but maybe only  ​/dataset​/{key}​/nameusage​/suggest works?

### ISSUE THREAD

**Issue by sckott** [CatalogueOfLife/backend#930]
```
curl -X GET "https://api.catalogueoflife.org/nameusage/suggest?q=Apis" -H  "accept: application/json"
```

gives

```
{"code":400,"message":"Missing/invalid datasetKey parameter"}
```

whereas `curl -X GET "https://api.catalogueoflife.org/dataset/3/nameusage/suggest?q=Apis" -H  "accept: application/json"` works

**Comment by mdoering** [comment]
Yes, you cannot use the suggest service across all datasets in checklistbank but it requires a specific dataset.
The resource path `/dataset/3/nameusage/` contains the datasetKey in the path and restricts the suggest to dataset 3 (which is the unpublished project you probably do not want to use. More below) whereas `/nameusage` is a global resource across all datasets. The regular search for example does allow that. It is mostly a convenience method to have the nameusage resource exposed in 2 ways. Scoping by dataset in the path is quite comfortable.

Otherwise you can also use a query parameter `datasetKey=3` in the global resource to restrict the suggest:
`https://api.catalogueoflife.org/nameusage/suggest?datasetKey=3LR&q=Apis`

datasetKey=3LR is the LatestRelease of dataset 3, which is a consistent, immutable snapshot and can be cached by the backend

**Comment by mdoering** [comment]
well, the docs should mention datasetKey is required

**Comment by sckott** [comment]
Thanks. Hmm, so shouldn't this route https://api.catalogueoflife.org/#/default/suggest (`/nameusage/suggest` without a datasetKey) be removed then?

**Comment by mdoering** [comment]
I guess so. Or I simply remove that required datasetKey constraint. Does it make sense to have an autocomplete across all datasets?

**Comment by sckott** [comment]
Oof, I don't know. I could imagine users wanting to search across datasets, but I don't know if that makes sense from your perspective

**Comment by mdoering** [comment]
the suggest response actually does not even include a datasetKey, just the usageID which is scoped within a single datasetKey so not unique across. I will remove that resource alltogether, it makes no sense, and just leave the proper search

**Comment by sckott** [comment]
thanks much
