### ISSUE TITLE
Improve Ecological Metadata Language (EML) support

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#972]
A lot of the fields in Ecological Metadata Language are not mapping to the CoL metadata fields. For example, see [this dataset](https://data.dev.catalogueoflife.org/dataset/2094/meta) and I'll email the eml.xml to you because it includes a lot of people's email addresses.

Fields that aren't mapping are:
- authors
- editors
- organizationName :arrow_right: organisations
- geographicCoverage :arrow_right: geographicScope
- taxonomicCoverage :arrow_right: taxonomicGroup
- resourceLogoUrl :arrow_right: logo
- dateStamp :arrow_right: version

Fields not supported by EML, but possibly could be included in the additionalMetadata section under col:
- alias
- completeness
- confidence
- license?

```xml
<additionalMetadata>                                                         
<metadata>      
<col>
<alias>WoRMS </alias>
<completeness>100</completeness>
<confidence>5</confidence>
<license>cc-by</license>
</col>                                                            
<gbif>                                                                     
<dateStamp>2021-03-01T09:32:36+01:00</dateStamp>                         
<hierarchyLevel>dataset</hierarchyLevel>                                 
<citation>&lt;b&gt;WoRMS Editorial Board&lt;/b&gt; (2021). World Register of Marine Species. Available from http://www.marinespecies.org at VLIZ. Accessed 2021-03-01. doi:10.14284/170</citation>
<resourceLogoUrl>http://www.marinespecies.org/documents/WoRMS%20branding/WoRMS_logo_blue_negative.png</resourceLogoUrl>
</gbif>                                                                    
</metadata>                                                                 
</additionalMetadata> 
```

Related: https://github.com/CatalogueOfLife/coldp/issues/43

**Comment by mdoering** [comment]
license is part of the main EML block:


I usually use VASCAN as a reference for a rather complete and well maintained EML document:
https://api.gbif.org/v1/dataset/3f8a1297-3259-4700-91fc-acc4170b27ce/document

Parsing geographicCoverage and organizationName is not at all simple, but I agree we should be doing this.
COL decided to list organisations separate from the authors/editors. Thats different to how EML handles this.
Conversion therefore needs a bit more of logic to normalize organisations, but I agree we should be doing this.

**Comment by mdoering** [comment]
about timestamp I am not 100% sure.
All these timestamps and version fields are easily mixed up.

In EML you have `pubDate` which is the date the data has been published. This is currently mapped to `released` in COL.
dateStamp in EML is the time the metadata was last modified - not sure if that maps anywhere in our model. Version seems wrong to me.

Adding a col section under additionalMetadata is a good idea, lets promote that! But lets decide what goes into this sections exactly. completeness & confidence are clear candidates. Alias might be elsewhere already, I need to check.

**Comment by mdoering** [comment]
Mapping taxonomicCoverage ➡️ taxonomicGroup seems dangerous. Take a look at the VASCAN example.
Would you expect hundreds of taxa in the taxonomicGroup field? I think we rather want a single or few names in there, but maybe that doesn't matter

**Comment by gdower** [comment]
In order of priority, at least getting these fields mapped is really important for WoRMS specifically, and could be a blocker for the next monthly release because some of the WoRMS datasets are assembled for the next release:

- authors
- editors
- organizationName
- logo

Short-term, maybe we could loop through the authors and editors to collect their organizations and then put them in the organizations field? Longer-term, relating authors/editors to their host organizations seems like something we probably should be doing in metadata.yaml, too.

**Comment by mdoering** [comment]
well, there are no explicit authors or editors in EML.
We currently already map the following fields from EML:

 - shortName = alias
 - title = title
 - abstract = description
 - distribution/online/url = website
 - intellectualRights/para/ulink
 - pubDate = released
 - creator =+ author
 - contact = contact
 - additionalMetadata:
   - resourceLogoUrl = logo
   - citation = citation

The complex person type is mapped as:
 - userId = orcid
 - surName = familyName
 - givenName = givenName
 - electronicMailAddress = email


An EML Agent is a mix of organisation and person properties and can represent either of them:

```
<contact>
	<individualName>
		<givenName>Luc</givenName>
		<surName>Brouillet</surName>
	</individualName>
	<organizationName>Université de Montréal Biodiversity Centre</organizationName>
	<positionName>Professor</positionName>
	<address>
		<deliveryPoint>4101 rue Sherbrooke est</deliveryPoint>
		<city>Montreal</city>
		<administrativeArea>Quebec</administrativeArea>
		<postalCode>H1X2B2</postalCode>
		<country>CANADA</country>
	</address>
	<electronicMailAddress>luc.brouillet@umontreal.ca</electronicMailAddress>
	<onlineUrl>http://www.irbv.umontreal.ca/luc-brouillet</onlineUrl>
</contact>
```
You can find just `organizationName`, just `individualName` or both in which case I think of such an agent as a person associated with an organisation. The address could also relate to both, so that it is not necessarily clear if its the organisations address or the persons private one. 

In COL we hold country, state, city, institution and department properties for an organisation.
I could try to extract the unique list of organisations with their address from EML.
Maybe its also worth extending our person and organisation class with a URL?

There are potentially further flexible agents in an EML document which that we could harvest. These can have a free text `role` element. These are in both
 - associatedParty 
 - project/personnel/*

For example:
```
<personnel>
  <individualName>
    <givenName>Luc</givenName>
    <surName>Brouillet</surName>
  </individualName>
<role>EDITOR</role>
</personnel>
```

We could blindly add all agents to authors, but that seems dangerous.
There are these roles defined by GBIF: https://rs.gbif.org/vocabulary/gbif/agent_role.xml
But there can be others too.

Suggest to map the following roles:

 - author = author
 - contentProvider = author
 - originator = author
 - custodianSteward = editor
 - editor = editor
 - pointOfContact = contact (if not already otherwise given)

What about `owner, principalInvestigator, processor, publisher, user, programmer, curator, reviewer` ???
For now I would better ignore them. What do you think?


Additionally I would propose to map also the following fields:

 - geographicCoverage/geographicDescription = geographicScope
 - taxonomicCoverage/generalTaxonomicCoverage = group (I would even consider to change the field to `taxonomicScope` similar how we treat `geographicScope`)
 - additionalMetadata/col/confidence = confidence
 - additionalMetadata/col/completeness = completeness
 - additionalMetadata/col/version = version


Another thing I always wondered if its worthwhile adding to Dataset is a list of `keywords`. These are also in EML.

**Comment by mdoering** [comment]
... or we adopt the same mixed model in COL? Thats quite a change, but also more compatible with GBIF:
http://api.gbif.org/v1/dataset/3f8a1297-3259-4700-91fc-acc4170b27ce/

**Comment by mdoering** [comment]
maybe we should add a catch all associated list of persons to our metadata? That could hold all agents with other roles such as programmers?

**Comment by mdoering** [comment]
EML parser updated. Changes left for discussion:

 - taxonomicCoverage/generalTaxonomicCoverage = new taxonomicScope ?
 - additionalMetadata/col/version = version ?
 - merge Person & Organisation into Agent ?

**Comment by gdower** [comment]
For the roles, we probably should only map authors = authors and editors = editors. Longer-term, adding those other roles to the metadata page would be good because those people should be credited, too, but those other roles are still distinct from the roles of authors and editors.

**Comment by mdoering** [comment]
FIne with that too, it's probably safer and cleaner anyways. Will do that
